#!/bin/bash

if [ -z "" ];
then

cat <<EOF
test_ignore=yes
EOF
  
exit

fi

source /home/sdruix/mcxx/tests/config/mercurium-libraries

cat <<EOF
MCC="/home/sdruix/mcxx/src/driver/mcxx --output-dir=/home/sdruix/mcxx/tests --profile=mcc --config-dir=/home/sdruix/mcxx/config --verbose"
MCXX="/home/sdruix/mcxx/src/driver/mcxx --output-dir=/home/sdruix/mcxx/tests --profile=mcxx --config-dir=/home/sdruix/mcxx/config --verbose"
EOF

if [ ! -z "" ];
then

cat <<EOF
compile_versions="nanos4_plain"
EOF

cat <<EOF
test_CC_nanos4_plain="\${MCC}"
test_CXX_nanos4_plain="\${MCXX}"

test_CFLAGS_nanos4_plain=
test_CXXFLAGS_nanos4_plain=
EOF

if [ ! -z "" ];
then

cat <<EOF
compile_versions="\${compile_versions} nanos4_instrument"

test_CC_nanos4_instrument="\${test_CC_nanos4_plain}"
test_CXX_nanos4_instrument="\${test_CXX_nanos4_plain}"

test_CFLAGS_nanos4_instrument="\${test_CFLAGS_nanos4_plain} --instrument"
test_CXXFLAGS_nanos4_instrument="\${test_CXXFLAGS_nanos4_plain} --instrument"
EOF

fi

fi

cat <<EOF
test_nolink=yes
EOF
