#!/bin/bash

with_regions="no"

if [ x$1 = xregions ];
then
    with_regions="yes"
fi


# If no Nanos++ or no superscalar, exit
if [ -z "" -o "no" = "no" ];
then

cat <<EOF
test_ignore=yes
EOF
  
exit

fi

# If Nanos++ and superscalar but no regions and regions were requested, exit
if [ $with_regions = yes -a "no" = "no" ];
then

cat <<EOF
test_ignore=yes
EOF

exit

fi

source /home/sdruix/mcxx/tests/config/mercurium-libraries

cat <<EOF
MCC="/home/sdruix/mcxx/src/driver/mcxx --output-dir=/home/sdruix/mcxx/tests --profile=sscc --config-dir=/home/sdruix/mcxx/config --verbose"
MCXX="/home/sdruix/mcxx/src/driver/mcxx --output-dir=/home/sdruix/mcxx/tests --profile=sscxx --config-dir=/home/sdruix/mcxx/config --verbose"
EOF

if [ ! -z "" ];
then

cat <<EOF
compile_versions="\${compile_versions} sscc_plain sscc_no_xlate"

test_CC_sscc_plain="\${MCC}"
test_CXX_sscc_plain="\${MCXX}"

test_CC_sscc_no_xlate="\${MCC}"
test_CXX_sscc_no_xlate="\${MCXX}"

test_CFLAGS_sscc_no_xlate="--variable=do_not_create_translation_function:1"
test_CXXFLAGS_sscc_no_xlate="--variable=do_not_create_translation_function:1"
EOF

fi
