#!/bin/bash

with_regions="no"

if [ x$1 = xregions ];
then
    with_regions="yes"
fi

if [ -z "" ];
then

cat <<EOF
test_ignore=yes
EOF
  
exit

fi

# If Nanos++ and superscalar but no regions and regions were requested, exit
if [ $with_regions = yes -a "no" = "no" ];
then

cat <<EOF
test_ignore=yes
EOF

exit

fi

source /home/sdruix/mcxx/tests/config/mercurium-libraries

cat <<EOF
MCC="/home/sdruix/mcxx/src/driver/mcxx --output-dir=/home/sdruix/mcxx/tests --profile=mcc --config-dir=/home/sdruix/mcxx/config --verbose"
MCXX="/home/sdruix/mcxx/src/driver/mcxx --output-dir=/home/sdruix/mcxx/tests --profile=mcxx --config-dir=/home/sdruix/mcxx/config --verbose"
EOF

if [ ! -z "" ];
then

cat <<EOF
compile_versions="\${compile_versions} nanox_plain nanox_no_xlate"

#plain
test_CC_nanox_plain="\${MCC}"
test_CXX_nanox_plain="\${MCXX}"

test_CFLAGS_nanox_plain="--nanox -std=gnu99"
test_CXXFLAGS_nanox_plain="--nanox"

#no_xlate

test_CC_nanox_no_xlate="\${MCC}"
test_CXX_nanox_no_xlate="\${MCXX}"

test_CFLAGS_nanox_no_xlate="--nanox -std=gnu99 --variable=do_not_create_translation_function:1"
test_CXXFLAGS_nanox_no_xlate="--nanox --variable=do_not_create_translation_function:1"

EOF

if [ ! -z "" ];
then

cat <<EOF
compile_versions="\${compile_versions} nanox_instrument"

test_CC_nanox_instrument="\${MCC}"
test_CXX_nanox_instrument="\${MCXX}"

test_CFLAGS_nanox_instrument="\${test_CFLAGS_nanox_plain} --instrument"
test_CXXFLAGS_nanox_instrument="\${test_CXXFLAGS_nanox_plain} --instrument"
EOF

fi

fi
