#!/bin/bash

if [ "no" = "no" ];
then

cat <<EOF
test_ignore=yes
EOF

fi

cat <<EOF
compile_versions=API_none
EOF

source /home/sdruix/mcxx/tests/config/mercurium-libraries

cat <<EOF
MCC="/home/sdruix/mcxx/src/driver/mcxx --output-dir=/home/sdruix/mcxx/tests --profile=smpss-cc --config-dir=/home/sdruix/mcxx/config -I/home/sdruix/mcxx/../../master --verbose"

test_CC_API_3="\${MCC}"
test_CC_API_4="\${MCC}"
test_CC_API_5="\${MCC}"

test_CFLAGS=--gcc

test_nolink=yes
EOF
