#!/bin/bash

source /home/sdruix/mcxx/tests/config/mercurium-libraries

cat <<EOF
MCXX="/home/sdruix/mcxx/libtool --mode=execute ${LIBTOOL_LIBRARIES} /home/sdruix/mcxx/src/driver/mcxx --output-dir=/home/sdruix/mcxx/tests --config-file=/home/sdruix/mcxx/tests/06_phases_hlt.dg/config.mcxx"
test_CC="\${MCXX} --profile=hltcc"
test_CXX="\${MCXX} --profile=hltcxx"
test_CFLAGS="--hlt --variable=allow_identity:false"
test_CXXFLAGS="--hlt --variable=allow_identity:false"
test_nolink=yes
EOF
