typedef unsigned int size_t;
extern void *memcpy(void *__restrict __dest, const void *__restrict __src, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern void *memmove(void *__dest, const void *__src, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern void *memccpy(void *__restrict __dest, const void *__restrict __src, int __c, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern void *memset(void *__s, int __c, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)));
extern int memcmp(const void *__s1, const void *__s2, size_t __n) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern void *memchr(const void *__s, int __c, size_t __n) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1)));
extern char *strcpy(char *__restrict __dest, const char *__restrict __src) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern char *strncpy(char *__restrict __dest, const char *__restrict __src, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern char *strcat(char *__restrict __dest, const char *__restrict __src) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern char *strncat(char *__restrict __dest, const char *__restrict __src, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern int strcmp(const char *__s1, const char *__s2) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern int strncmp(const char *__s1, const char *__s2, size_t __n) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern int strcoll(const char *__s1, const char *__s2) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern size_t strxfrm(char *__restrict __dest, const char *__restrict __src, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)));
typedef struct __locale_struct
{
        struct __locale_data *__locales[13];
        const unsigned short int *__ctype_b;
        const int *__ctype_tolower;
        const int *__ctype_toupper;
        const char *__names[13];
} *__locale_t;
typedef __locale_t locale_t;
extern int strcoll_l(const char *__s1, const char *__s2, __locale_t __l) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2, 3)));
extern size_t strxfrm_l(char *__dest, const char *__src, size_t __n, __locale_t __l) __attribute__((__nothrow__)) __attribute__((__nonnull__(2, 4)));
extern char *strdup(const char *__s) __attribute__((__nothrow__)) __attribute__((__malloc__)) __attribute__((__nonnull__(1)));
extern char *strndup(const char *__string, size_t __n) __attribute__((__nothrow__)) __attribute__((__malloc__)) __attribute__((__nonnull__(1)));
extern char *strchr(const char *__s, int __c) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1)));
extern char *strrchr(const char *__s, int __c) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1)));
extern size_t strcspn(const char *__s, const char *__reject) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern size_t strspn(const char *__s, const char *__accept) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern char *strpbrk(const char *__s, const char *__accept) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern char *strstr(const char *__haystack, const char *__needle) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern char *strtok(char *__restrict __s, const char *__restrict __delim) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)));
extern char *__strtok_r(char *__restrict __s, const char *__restrict __delim, char **__restrict __save_ptr) __attribute__((__nothrow__)) __attribute__((__nonnull__(2, 3)));
extern char *strtok_r(char *__restrict __s, const char *__restrict __delim, char **__restrict __save_ptr) __attribute__((__nothrow__)) __attribute__((__nonnull__(2, 3)));
extern size_t strlen(const char *__s) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1)));
extern size_t strnlen(const char *__string, size_t __maxlen) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1)));
extern char *strerror(int __errnum) __attribute__((__nothrow__));
extern int strerror_r(int __errnum, char *__buf, size_t __buflen) __asm__ ("""__xpg_strerror_r") __attribute__((__nothrow__)) __attribute__((__nonnull__(2)));
extern char *strerror_l(int __errnum, __locale_t __l) __attribute__((__nothrow__));
extern void __bzero(void *__s, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)));
extern void bcopy(const void *__src, void *__dest, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern void bzero(void *__s, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1)));
extern int bcmp(const void *__s1, const void *__s2, size_t __n) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern char *index(const char *__s, int __c) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1)));
extern char *rindex(const char *__s, int __c) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1)));
extern int ffs(int __i) __attribute__((__nothrow__)) __attribute__((__const__));
extern int strcasecmp(const char *__s1, const char *__s2) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern int strncasecmp(const char *__s1, const char *__s2, size_t __n) __attribute__((__nothrow__)) __attribute__((__pure__)) __attribute__((__nonnull__(1, 2)));
extern char *strsep(char **__restrict __stringp, const char *__restrict __delim) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern char *strsignal(int __sig) __attribute__((__nothrow__));
extern char *__stpcpy(char *__restrict __dest, const char *__restrict __src) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern char *stpcpy(char *__restrict __dest, const char *__restrict __src) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern char *__stpncpy(char *__restrict __dest, const char *__restrict __src, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
extern char *stpncpy(char *__restrict __dest, const char *__restrict __src, size_t __n) __attribute__((__nothrow__)) __attribute__((__nonnull__(1, 2)));
typedef long double float_t;
typedef long double double_t;
extern double acos(double __x) __attribute__((__nothrow__));
extern double __acos(double __x) __attribute__((__nothrow__));
extern double asin(double __x) __attribute__((__nothrow__));
extern double __asin(double __x) __attribute__((__nothrow__));
extern double atan(double __x) __attribute__((__nothrow__));
extern double __atan(double __x) __attribute__((__nothrow__));
extern double atan2(double __y, double __x) __attribute__((__nothrow__));
extern double __atan2(double __y, double __x) __attribute__((__nothrow__));
extern double cos(double __x) __attribute__((__nothrow__));
extern double __cos(double __x) __attribute__((__nothrow__));
extern double sin(double __x) __attribute__((__nothrow__));
extern double __sin(double __x) __attribute__((__nothrow__));
extern double tan(double __x) __attribute__((__nothrow__));
extern double __tan(double __x) __attribute__((__nothrow__));
extern double cosh(double __x) __attribute__((__nothrow__));
extern double __cosh(double __x) __attribute__((__nothrow__));
extern double sinh(double __x) __attribute__((__nothrow__));
extern double __sinh(double __x) __attribute__((__nothrow__));
extern double tanh(double __x) __attribute__((__nothrow__));
extern double __tanh(double __x) __attribute__((__nothrow__));
extern double acosh(double __x) __attribute__((__nothrow__));
extern double __acosh(double __x) __attribute__((__nothrow__));
extern double asinh(double __x) __attribute__((__nothrow__));
extern double __asinh(double __x) __attribute__((__nothrow__));
extern double atanh(double __x) __attribute__((__nothrow__));
extern double __atanh(double __x) __attribute__((__nothrow__));
extern double exp(double __x) __attribute__((__nothrow__));
extern double __exp(double __x) __attribute__((__nothrow__));
extern double frexp(double __x, int *__exponent) __attribute__((__nothrow__));
extern double __frexp(double __x, int *__exponent) __attribute__((__nothrow__));
extern double ldexp(double __x, int __exponent) __attribute__((__nothrow__));
extern double __ldexp(double __x, int __exponent) __attribute__((__nothrow__));
extern double log(double __x) __attribute__((__nothrow__));
extern double __log(double __x) __attribute__((__nothrow__));
extern double log10(double __x) __attribute__((__nothrow__));
extern double __log10(double __x) __attribute__((__nothrow__));
extern double modf(double __x, double *__iptr) __attribute__((__nothrow__));
extern double __modf(double __x, double *__iptr) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)));
extern double expm1(double __x) __attribute__((__nothrow__));
extern double __expm1(double __x) __attribute__((__nothrow__));
extern double log1p(double __x) __attribute__((__nothrow__));
extern double __log1p(double __x) __attribute__((__nothrow__));
extern double logb(double __x) __attribute__((__nothrow__));
extern double __logb(double __x) __attribute__((__nothrow__));
extern double exp2(double __x) __attribute__((__nothrow__));
extern double __exp2(double __x) __attribute__((__nothrow__));
extern double log2(double __x) __attribute__((__nothrow__));
extern double __log2(double __x) __attribute__((__nothrow__));
extern double pow(double __x, double __y) __attribute__((__nothrow__));
extern double __pow(double __x, double __y) __attribute__((__nothrow__));
extern double sqrt(double __x) __attribute__((__nothrow__));
extern double __sqrt(double __x) __attribute__((__nothrow__));
extern double hypot(double __x, double __y) __attribute__((__nothrow__));
extern double __hypot(double __x, double __y) __attribute__((__nothrow__));
extern double cbrt(double __x) __attribute__((__nothrow__));
extern double __cbrt(double __x) __attribute__((__nothrow__));
extern double ceil(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __ceil(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double fabs(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __fabs(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double floor(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __floor(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double fmod(double __x, double __y) __attribute__((__nothrow__));
extern double __fmod(double __x, double __y) __attribute__((__nothrow__));
extern int __isinf(double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __finite(double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int isinf(double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int finite(double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern double drem(double __x, double __y) __attribute__((__nothrow__));
extern double __drem(double __x, double __y) __attribute__((__nothrow__));
extern double significand(double __x) __attribute__((__nothrow__));
extern double __significand(double __x) __attribute__((__nothrow__));
extern double copysign(double __x, double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __copysign(double __x, double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double nan(const char *__tagb) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __nan(const char *__tagb) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __isnan(double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int isnan(double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern double j0(double) __attribute__((__nothrow__));
extern double __j0(double) __attribute__((__nothrow__));
extern double j1(double) __attribute__((__nothrow__));
extern double __j1(double) __attribute__((__nothrow__));
extern double jn(int, double) __attribute__((__nothrow__));
extern double __jn(int, double) __attribute__((__nothrow__));
extern double y0(double) __attribute__((__nothrow__));
extern double __y0(double) __attribute__((__nothrow__));
extern double y1(double) __attribute__((__nothrow__));
extern double __y1(double) __attribute__((__nothrow__));
extern double yn(int, double) __attribute__((__nothrow__));
extern double __yn(int, double) __attribute__((__nothrow__));
extern double erf(double) __attribute__((__nothrow__));
extern double __erf(double) __attribute__((__nothrow__));
extern double erfc(double) __attribute__((__nothrow__));
extern double __erfc(double) __attribute__((__nothrow__));
extern double lgamma(double) __attribute__((__nothrow__));
extern double __lgamma(double) __attribute__((__nothrow__));
extern double tgamma(double) __attribute__((__nothrow__));
extern double __tgamma(double) __attribute__((__nothrow__));
extern double gamma(double) __attribute__((__nothrow__));
extern double __gamma(double) __attribute__((__nothrow__));
extern double lgamma_r(double, int *__signgamp) __attribute__((__nothrow__));
extern double __lgamma_r(double, int *__signgamp) __attribute__((__nothrow__));
extern double rint(double __x) __attribute__((__nothrow__));
extern double __rint(double __x) __attribute__((__nothrow__));
extern double nextafter(double __x, double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __nextafter(double __x, double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double nexttoward(double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __nexttoward(double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double remainder(double __x, double __y) __attribute__((__nothrow__));
extern double __remainder(double __x, double __y) __attribute__((__nothrow__));
extern double scalbn(double __x, int __n) __attribute__((__nothrow__));
extern double __scalbn(double __x, int __n) __attribute__((__nothrow__));
extern int ilogb(double __x) __attribute__((__nothrow__));
extern int __ilogb(double __x) __attribute__((__nothrow__));
extern double scalbln(double __x, long int __n) __attribute__((__nothrow__));
extern double __scalbln(double __x, long int __n) __attribute__((__nothrow__));
extern double nearbyint(double __x) __attribute__((__nothrow__));
extern double __nearbyint(double __x) __attribute__((__nothrow__));
extern double round(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __round(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double trunc(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __trunc(double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern double remquo(double __x, double __y, int *__quo) __attribute__((__nothrow__));
extern double __remquo(double __x, double __y, int *__quo) __attribute__((__nothrow__));
extern long int lrint(double __x) __attribute__((__nothrow__));
extern long int __lrint(double __x) __attribute__((__nothrow__));
__extension__
extern long long int llrint(double __x) __attribute__((__nothrow__));
extern long long int __llrint(double __x) __attribute__((__nothrow__));
extern long int lround(double __x) __attribute__((__nothrow__));
extern long int __lround(double __x) __attribute__((__nothrow__));
__extension__
extern long long int llround(double __x) __attribute__((__nothrow__));
extern long long int __llround(double __x) __attribute__((__nothrow__));
extern double fdim(double __x, double __y) __attribute__((__nothrow__));
extern double __fdim(double __x, double __y) __attribute__((__nothrow__));
extern double fmax(double __x, double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __fmax(double __x, double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double fmin(double __x, double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern double __fmin(double __x, double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __fpclassify(double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __signbit(double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern double fma(double __x, double __y, double __z) __attribute__((__nothrow__));
extern double __fma(double __x, double __y, double __z) __attribute__((__nothrow__));
extern double scalb(double __x, double __n) __attribute__((__nothrow__));
extern double __scalb(double __x, double __n) __attribute__((__nothrow__));
extern float acosf(float __x) __attribute__((__nothrow__));
extern float __acosf(float __x) __attribute__((__nothrow__));
extern float asinf(float __x) __attribute__((__nothrow__));
extern float __asinf(float __x) __attribute__((__nothrow__));
extern float atanf(float __x) __attribute__((__nothrow__));
extern float __atanf(float __x) __attribute__((__nothrow__));
extern float atan2f(float __y, float __x) __attribute__((__nothrow__));
extern float __atan2f(float __y, float __x) __attribute__((__nothrow__));
extern float cosf(float __x) __attribute__((__nothrow__));
extern float __cosf(float __x) __attribute__((__nothrow__));
extern float sinf(float __x) __attribute__((__nothrow__));
extern float __sinf(float __x) __attribute__((__nothrow__));
extern float tanf(float __x) __attribute__((__nothrow__));
extern float __tanf(float __x) __attribute__((__nothrow__));
extern float coshf(float __x) __attribute__((__nothrow__));
extern float __coshf(float __x) __attribute__((__nothrow__));
extern float sinhf(float __x) __attribute__((__nothrow__));
extern float __sinhf(float __x) __attribute__((__nothrow__));
extern float tanhf(float __x) __attribute__((__nothrow__));
extern float __tanhf(float __x) __attribute__((__nothrow__));
extern float acoshf(float __x) __attribute__((__nothrow__));
extern float __acoshf(float __x) __attribute__((__nothrow__));
extern float asinhf(float __x) __attribute__((__nothrow__));
extern float __asinhf(float __x) __attribute__((__nothrow__));
extern float atanhf(float __x) __attribute__((__nothrow__));
extern float __atanhf(float __x) __attribute__((__nothrow__));
extern float expf(float __x) __attribute__((__nothrow__));
extern float __expf(float __x) __attribute__((__nothrow__));
extern float frexpf(float __x, int *__exponent) __attribute__((__nothrow__));
extern float __frexpf(float __x, int *__exponent) __attribute__((__nothrow__));
extern float ldexpf(float __x, int __exponent) __attribute__((__nothrow__));
extern float __ldexpf(float __x, int __exponent) __attribute__((__nothrow__));
extern float logf(float __x) __attribute__((__nothrow__));
extern float __logf(float __x) __attribute__((__nothrow__));
extern float log10f(float __x) __attribute__((__nothrow__));
extern float __log10f(float __x) __attribute__((__nothrow__));
extern float modff(float __x, float *__iptr) __attribute__((__nothrow__));
extern float __modff(float __x, float *__iptr) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)));
extern float expm1f(float __x) __attribute__((__nothrow__));
extern float __expm1f(float __x) __attribute__((__nothrow__));
extern float log1pf(float __x) __attribute__((__nothrow__));
extern float __log1pf(float __x) __attribute__((__nothrow__));
extern float logbf(float __x) __attribute__((__nothrow__));
extern float __logbf(float __x) __attribute__((__nothrow__));
extern float exp2f(float __x) __attribute__((__nothrow__));
extern float __exp2f(float __x) __attribute__((__nothrow__));
extern float log2f(float __x) __attribute__((__nothrow__));
extern float __log2f(float __x) __attribute__((__nothrow__));
extern float powf(float __x, float __y) __attribute__((__nothrow__));
extern float __powf(float __x, float __y) __attribute__((__nothrow__));
extern float sqrtf(float __x) __attribute__((__nothrow__));
extern float __sqrtf(float __x) __attribute__((__nothrow__));
extern float hypotf(float __x, float __y) __attribute__((__nothrow__));
extern float __hypotf(float __x, float __y) __attribute__((__nothrow__));
extern float cbrtf(float __x) __attribute__((__nothrow__));
extern float __cbrtf(float __x) __attribute__((__nothrow__));
extern float ceilf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __ceilf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float fabsf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __fabsf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float floorf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __floorf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float fmodf(float __x, float __y) __attribute__((__nothrow__));
extern float __fmodf(float __x, float __y) __attribute__((__nothrow__));
extern int __isinff(float __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __finitef(float __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int isinff(float __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int finitef(float __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern float dremf(float __x, float __y) __attribute__((__nothrow__));
extern float __dremf(float __x, float __y) __attribute__((__nothrow__));
extern float significandf(float __x) __attribute__((__nothrow__));
extern float __significandf(float __x) __attribute__((__nothrow__));
extern float copysignf(float __x, float __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __copysignf(float __x, float __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float nanf(const char *__tagb) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __nanf(const char *__tagb) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __isnanf(float __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int isnanf(float __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern float j0f(float) __attribute__((__nothrow__));
extern float __j0f(float) __attribute__((__nothrow__));
extern float j1f(float) __attribute__((__nothrow__));
extern float __j1f(float) __attribute__((__nothrow__));
extern float jnf(int, float) __attribute__((__nothrow__));
extern float __jnf(int, float) __attribute__((__nothrow__));
extern float y0f(float) __attribute__((__nothrow__));
extern float __y0f(float) __attribute__((__nothrow__));
extern float y1f(float) __attribute__((__nothrow__));
extern float __y1f(float) __attribute__((__nothrow__));
extern float ynf(int, float) __attribute__((__nothrow__));
extern float __ynf(int, float) __attribute__((__nothrow__));
extern float erff(float) __attribute__((__nothrow__));
extern float __erff(float) __attribute__((__nothrow__));
extern float erfcf(float) __attribute__((__nothrow__));
extern float __erfcf(float) __attribute__((__nothrow__));
extern float lgammaf(float) __attribute__((__nothrow__));
extern float __lgammaf(float) __attribute__((__nothrow__));
extern float tgammaf(float) __attribute__((__nothrow__));
extern float __tgammaf(float) __attribute__((__nothrow__));
extern float gammaf(float) __attribute__((__nothrow__));
extern float __gammaf(float) __attribute__((__nothrow__));
extern float lgammaf_r(float, int *__signgamp) __attribute__((__nothrow__));
extern float __lgammaf_r(float, int *__signgamp) __attribute__((__nothrow__));
extern float rintf(float __x) __attribute__((__nothrow__));
extern float __rintf(float __x) __attribute__((__nothrow__));
extern float nextafterf(float __x, float __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __nextafterf(float __x, float __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float nexttowardf(float __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __nexttowardf(float __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float remainderf(float __x, float __y) __attribute__((__nothrow__));
extern float __remainderf(float __x, float __y) __attribute__((__nothrow__));
extern float scalbnf(float __x, int __n) __attribute__((__nothrow__));
extern float __scalbnf(float __x, int __n) __attribute__((__nothrow__));
extern int ilogbf(float __x) __attribute__((__nothrow__));
extern int __ilogbf(float __x) __attribute__((__nothrow__));
extern float scalblnf(float __x, long int __n) __attribute__((__nothrow__));
extern float __scalblnf(float __x, long int __n) __attribute__((__nothrow__));
extern float nearbyintf(float __x) __attribute__((__nothrow__));
extern float __nearbyintf(float __x) __attribute__((__nothrow__));
extern float roundf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __roundf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float truncf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __truncf(float __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern float remquof(float __x, float __y, int *__quo) __attribute__((__nothrow__));
extern float __remquof(float __x, float __y, int *__quo) __attribute__((__nothrow__));
extern long int lrintf(float __x) __attribute__((__nothrow__));
extern long int __lrintf(float __x) __attribute__((__nothrow__));
__extension__
extern long long int llrintf(float __x) __attribute__((__nothrow__));
extern long long int __llrintf(float __x) __attribute__((__nothrow__));
extern long int lroundf(float __x) __attribute__((__nothrow__));
extern long int __lroundf(float __x) __attribute__((__nothrow__));
__extension__
extern long long int llroundf(float __x) __attribute__((__nothrow__));
extern long long int __llroundf(float __x) __attribute__((__nothrow__));
extern float fdimf(float __x, float __y) __attribute__((__nothrow__));
extern float __fdimf(float __x, float __y) __attribute__((__nothrow__));
extern float fmaxf(float __x, float __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __fmaxf(float __x, float __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float fminf(float __x, float __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern float __fminf(float __x, float __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __fpclassifyf(float __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __signbitf(float __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern float fmaf(float __x, float __y, float __z) __attribute__((__nothrow__));
extern float __fmaf(float __x, float __y, float __z) __attribute__((__nothrow__));
extern float scalbf(float __x, float __n) __attribute__((__nothrow__));
extern float __scalbf(float __x, float __n) __attribute__((__nothrow__));
extern long double acosl(long double __x) __attribute__((__nothrow__));
extern long double __acosl(long double __x) __attribute__((__nothrow__));
extern long double asinl(long double __x) __attribute__((__nothrow__));
extern long double __asinl(long double __x) __attribute__((__nothrow__));
extern long double atanl(long double __x) __attribute__((__nothrow__));
extern long double __atanl(long double __x) __attribute__((__nothrow__));
extern long double atan2l(long double __y, long double __x) __attribute__((__nothrow__));
extern long double __atan2l(long double __y, long double __x) __attribute__((__nothrow__));
extern long double cosl(long double __x) __attribute__((__nothrow__));
extern long double __cosl(long double __x) __attribute__((__nothrow__));
extern long double sinl(long double __x) __attribute__((__nothrow__));
extern long double __sinl(long double __x) __attribute__((__nothrow__));
extern long double tanl(long double __x) __attribute__((__nothrow__));
extern long double __tanl(long double __x) __attribute__((__nothrow__));
extern long double coshl(long double __x) __attribute__((__nothrow__));
extern long double __coshl(long double __x) __attribute__((__nothrow__));
extern long double sinhl(long double __x) __attribute__((__nothrow__));
extern long double __sinhl(long double __x) __attribute__((__nothrow__));
extern long double tanhl(long double __x) __attribute__((__nothrow__));
extern long double __tanhl(long double __x) __attribute__((__nothrow__));
extern long double acoshl(long double __x) __attribute__((__nothrow__));
extern long double __acoshl(long double __x) __attribute__((__nothrow__));
extern long double asinhl(long double __x) __attribute__((__nothrow__));
extern long double __asinhl(long double __x) __attribute__((__nothrow__));
extern long double atanhl(long double __x) __attribute__((__nothrow__));
extern long double __atanhl(long double __x) __attribute__((__nothrow__));
extern long double expl(long double __x) __attribute__((__nothrow__));
extern long double __expl(long double __x) __attribute__((__nothrow__));
extern long double frexpl(long double __x, int *__exponent) __attribute__((__nothrow__));
extern long double __frexpl(long double __x, int *__exponent) __attribute__((__nothrow__));
extern long double ldexpl(long double __x, int __exponent) __attribute__((__nothrow__));
extern long double __ldexpl(long double __x, int __exponent) __attribute__((__nothrow__));
extern long double logl(long double __x) __attribute__((__nothrow__));
extern long double __logl(long double __x) __attribute__((__nothrow__));
extern long double log10l(long double __x) __attribute__((__nothrow__));
extern long double __log10l(long double __x) __attribute__((__nothrow__));
extern long double modfl(long double __x, long double *__iptr) __attribute__((__nothrow__));
extern long double __modfl(long double __x, long double *__iptr) __attribute__((__nothrow__)) __attribute__((__nonnull__(2)));
extern long double expm1l(long double __x) __attribute__((__nothrow__));
extern long double __expm1l(long double __x) __attribute__((__nothrow__));
extern long double log1pl(long double __x) __attribute__((__nothrow__));
extern long double __log1pl(long double __x) __attribute__((__nothrow__));
extern long double logbl(long double __x) __attribute__((__nothrow__));
extern long double __logbl(long double __x) __attribute__((__nothrow__));
extern long double exp2l(long double __x) __attribute__((__nothrow__));
extern long double __exp2l(long double __x) __attribute__((__nothrow__));
extern long double log2l(long double __x) __attribute__((__nothrow__));
extern long double __log2l(long double __x) __attribute__((__nothrow__));
extern long double powl(long double __x, long double __y) __attribute__((__nothrow__));
extern long double __powl(long double __x, long double __y) __attribute__((__nothrow__));
extern long double sqrtl(long double __x) __attribute__((__nothrow__));
extern long double __sqrtl(long double __x) __attribute__((__nothrow__));
extern long double hypotl(long double __x, long double __y) __attribute__((__nothrow__));
extern long double __hypotl(long double __x, long double __y) __attribute__((__nothrow__));
extern long double cbrtl(long double __x) __attribute__((__nothrow__));
extern long double __cbrtl(long double __x) __attribute__((__nothrow__));
extern long double ceill(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __ceill(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double fabsl(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __fabsl(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double floorl(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __floorl(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double fmodl(long double __x, long double __y) __attribute__((__nothrow__));
extern long double __fmodl(long double __x, long double __y) __attribute__((__nothrow__));
extern int __isinfl(long double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __finitel(long double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int isinfl(long double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int finitel(long double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double dreml(long double __x, long double __y) __attribute__((__nothrow__));
extern long double __dreml(long double __x, long double __y) __attribute__((__nothrow__));
extern long double significandl(long double __x) __attribute__((__nothrow__));
extern long double __significandl(long double __x) __attribute__((__nothrow__));
extern long double copysignl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __copysignl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double nanl(const char *__tagb) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __nanl(const char *__tagb) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __isnanl(long double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int isnanl(long double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double j0l(long double) __attribute__((__nothrow__));
extern long double __j0l(long double) __attribute__((__nothrow__));
extern long double j1l(long double) __attribute__((__nothrow__));
extern long double __j1l(long double) __attribute__((__nothrow__));
extern long double jnl(int, long double) __attribute__((__nothrow__));
extern long double __jnl(int, long double) __attribute__((__nothrow__));
extern long double y0l(long double) __attribute__((__nothrow__));
extern long double __y0l(long double) __attribute__((__nothrow__));
extern long double y1l(long double) __attribute__((__nothrow__));
extern long double __y1l(long double) __attribute__((__nothrow__));
extern long double ynl(int, long double) __attribute__((__nothrow__));
extern long double __ynl(int, long double) __attribute__((__nothrow__));
extern long double erfl(long double) __attribute__((__nothrow__));
extern long double __erfl(long double) __attribute__((__nothrow__));
extern long double erfcl(long double) __attribute__((__nothrow__));
extern long double __erfcl(long double) __attribute__((__nothrow__));
extern long double lgammal(long double) __attribute__((__nothrow__));
extern long double __lgammal(long double) __attribute__((__nothrow__));
extern long double tgammal(long double) __attribute__((__nothrow__));
extern long double __tgammal(long double) __attribute__((__nothrow__));
extern long double gammal(long double) __attribute__((__nothrow__));
extern long double __gammal(long double) __attribute__((__nothrow__));
extern long double lgammal_r(long double, int *__signgamp) __attribute__((__nothrow__));
extern long double __lgammal_r(long double, int *__signgamp) __attribute__((__nothrow__));
extern long double rintl(long double __x) __attribute__((__nothrow__));
extern long double __rintl(long double __x) __attribute__((__nothrow__));
extern long double nextafterl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __nextafterl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double nexttowardl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __nexttowardl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double remainderl(long double __x, long double __y) __attribute__((__nothrow__));
extern long double __remainderl(long double __x, long double __y) __attribute__((__nothrow__));
extern long double scalbnl(long double __x, int __n) __attribute__((__nothrow__));
extern long double __scalbnl(long double __x, int __n) __attribute__((__nothrow__));
extern int ilogbl(long double __x) __attribute__((__nothrow__));
extern int __ilogbl(long double __x) __attribute__((__nothrow__));
extern long double scalblnl(long double __x, long int __n) __attribute__((__nothrow__));
extern long double __scalblnl(long double __x, long int __n) __attribute__((__nothrow__));
extern long double nearbyintl(long double __x) __attribute__((__nothrow__));
extern long double __nearbyintl(long double __x) __attribute__((__nothrow__));
extern long double roundl(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __roundl(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double truncl(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __truncl(long double __x) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double remquol(long double __x, long double __y, int *__quo) __attribute__((__nothrow__));
extern long double __remquol(long double __x, long double __y, int *__quo) __attribute__((__nothrow__));
extern long int lrintl(long double __x) __attribute__((__nothrow__));
extern long int __lrintl(long double __x) __attribute__((__nothrow__));
__extension__
extern long long int llrintl(long double __x) __attribute__((__nothrow__));
extern long long int __llrintl(long double __x) __attribute__((__nothrow__));
extern long int lroundl(long double __x) __attribute__((__nothrow__));
extern long int __lroundl(long double __x) __attribute__((__nothrow__));
__extension__
extern long long int llroundl(long double __x) __attribute__((__nothrow__));
extern long long int __llroundl(long double __x) __attribute__((__nothrow__));
extern long double fdiml(long double __x, long double __y) __attribute__((__nothrow__));
extern long double __fdiml(long double __x, long double __y) __attribute__((__nothrow__));
extern long double fmaxl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __fmaxl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double fminl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double __fminl(long double __x, long double __y) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __fpclassifyl(long double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern int __signbitl(long double __value) __attribute__((__nothrow__)) __attribute__((__const__));
extern long double fmal(long double __x, long double __y, long double __z) __attribute__((__nothrow__));
extern long double __fmal(long double __x, long double __y, long double __z) __attribute__((__nothrow__));
extern long double scalbl(long double __x, long double __n) __attribute__((__nothrow__));
extern long double __scalbl(long double __x, long double __n) __attribute__((__nothrow__));
extern int signgam;
enum 
{
    FP_NAN = 0, 
    FP_INFINITE = 1, 
    FP_ZERO = 2, 
    FP_SUBNORMAL = 3, 
    FP_NORMAL = 4
};
typedef enum 
{
    _IEEE_ = - 1, 
    _SVID_, 
    _XOPEN_, 
    _POSIX_, 
    _ISOC_
} _LIB_VERSION_TYPE;
extern _LIB_VERSION_TYPE _LIB_VERSION;
struct exception
{
        int type;
        char *name;
        double arg1;
        double arg2;
        double retval;
};
extern int matherr(struct exception *__exc);
double alpha;
double A[4000][4000];
double B[4000][4000];
static void init_array()
{
    int i, j;
    alpha = 12435;
    for (i = 0;
        i < 4000;
        )
    {
        for (j = 0;
            j < 4000;
            )
        {
            A[i][j] = ((double) i * j) / 4000;
            B[i][j] = ((double) i * j + 1) / 4000;
            j++;
        }
        i++;
    }
}
int main(int argc, char **argv)
{
    int i, j, k;
    int n = 4000;
    init_array();
    mem_trace_def_array2d("B", 4000, 4000);
    mem_trace_def_mem("B", &B, sizeof(double), sizeof (B));
    for (i = 1;
        i < n;
        i++)
    {
        mem_trace_iter_start("loop1", "i", i);
        {
            for (j = 0;
                j < n;
                j++)
            {
                mem_trace_iter_start("loop1", "j", j);
                {
                    for (k = 0;
                        k < i;
                        k++)
                    {
                        if (1)
                        {
                            mem_trace_read("B", &B[i][j]);
                            mem_trace_write("B", &B[i][j]);
                            (B[i][j]++);
                        }
                        mem_trace_read("B", &B[j][k]);
                        mem_trace_read("B", &B[i][j]);
                        mem_trace_write("B", &B[i][j]);
                        (B[i][j] += alpha * A[i][k] * B[j][k]);
                    }
                }
                mem_trace_iter_end("loop1", "j", j);
            }
        }
        mem_trace_iter_end("loop1", "i", i);
    }
    return 0;
}
